var express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use(express.static('public'));
const routes = require('./routes');
app.use('/', routes);
const port = 3001;
app.listen(port, () => console.log(`Server started on http://localhost:${port}`));